"""empty message

Revision ID: 87f666ebbd6f
Revises: 0763d677d453
Create Date: 2026-02-11 19:35:07.098416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87f666ebbd6f'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('product', sa.Integer(), nullable=False),
                    sa.Column('date', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('operations',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('portfolio_id', sa.Integer(), nullable=False),
                    sa.Column('product', sa.Integer(), nullable=False),
                    sa.Column('date', sa.DateTime(), nullable=False),
                    sa.Column('total_price_spent', sa.Float(), nullable=True),
                    sa.Column('amount', sa.Float(), nullable=False),
                    sa.Column('bought', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['portfolio_id'], ['portfolio.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.add_column(
            sa.Column('last_name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('cash', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('cash')
        batch_op.drop_column('last_name')
        batch_op.drop_column('name')

    op.drop_table('operations')
    op.drop_table('portfolio')
    # ### end Alembic commands ###
